name: Python Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git clone ${{ github.repositoryUrl }} .
        git fetch --all
        git reset --hard origin/${{ github.ref }}

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install python3.8 python3.8-venv 
